### PR TITLE
Symfony 4 compatibility

### PR DESCRIPTION
**Pull request by mateuszsip**
Basically #326 with @weaverryan suggestions.

### CODE REVIEW

**Comment by mateuszsip** [comment]
4.0 build failing because composer needs a release.

docker build failing because of missing xdebug.

**Comment by jbgomond** [comment]
When will this be merged ? Thanks :)

ping @egeloen

**Comment by jbgomond** [comment]
@kejwmen Services in renderer.xml need to be public too :)

image

**Comment by mateuszsip** [comment]
I will fix it tomorrow, thanks!

**Comment by weaverryan** [comment]
Actually, I was a bit wrong when I originally said to make all services public that didn’t previously have a public attribute. In fact, you should only make a service public if it really should be used by the end user. If you don’t add a public attribute, then the user will see a deprecation warning if they try to use it directly from the container.

About the error, if the service in question really doesn’t need to be used directly by the end user, we should leave the public attribute alone and update the library itself to use dependency injection instead of fetching the service directly.

If I’ve made any incorrect assumptions about the library - apologies: I haven’t looked at the code in question :).

**Comment by mateuszsip** [comment]
@weaverryan you are totally right, I haven't looked at library code and was sure it requires significant amount of work so it would be better to start with simple compat PR.

PR has to wait for composer release and refactoring required to leave renderers private looks straightforward, I will take care of that.

Thanks you found some time to leave this comment ;)

**Comment by mateuszsip** [comment]
In current state installer script handler won't work with symfony 4 (needs `DistributionBundle`) and it was the only reason to require `composer` as a dev-dependency.
Looks that `composer` can be now completely optional and we don't have to wait for new release :tada: 

I don't know what @egeloen thinks about it, but at this point I made an assumption that support for symfony < 3.3 and php < 7 can be dropped.

If bundle needs that support some additional work is required, that's why I will wait for opinion.

And I would appreciate a code review, thanks!

**Comment by laminr** [comment]
any news for that PR ? I am sure that many waits as me to use it in S4 ;-)
Thanks for the work

**Comment by jbgomond** [comment]
ping @egeloen

**Comment by tjorim** [comment]
For now you can use the following lines in your composer.json to use the fork of @kejwmen :
```
{
    "require": {
        "egeloen/ckeditor-bundle": "dev-feature/symfony4-compat"
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/kejwmen/IvoryCKEditorBundle"
        }
    ]
}
```

As @egeloen stated on his Twitter on November 16th, he simply has no time and is looking for maintainers for the Ivory bundles: https://twitter.com/egeloen/status/931240338467049472

**Pull request closed without merging**
