### PR TITLE
Fixed deprecations related to getting container services

### LINKED ISSUE #323: Services will become private by default starting from Symfony 3.4
Services that need to public need to explicitly marked as public starting from Symfony 3.4. See http://symfony.com/blog/new-in-symfony-3-4-services-are-private-by-default

When updating a Symfony app using this bundle to Symfony 3.4, I saw these deprecation messages:

```
User Deprecated: The "ivory_ck_editor.renderer.json_builder" service is private,
getting it from the container is deprecated since Symfony 3.2 and will fail in
4.0. You should either make the service public, or stop using the container
directly and use dependency injection instead.

User Deprecated: The "assets.packages" service is private, getting it from the
container is deprecated since Symfony 3.2 and will fail in 4.0. You should
either make the service public, or stop using the container directly and use
dependency injection instead.
```

### PR DESCRIPTION
**Pull request by javiereguiluz**
This fixes #323.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
I'm closing this PR because it's wrong. #323 can be solved more easily. Thanks @weaverryan for the tip!

**Comment by peterrehm** [comment]
@javiereguiluz How did you fix it?

**Comment by ghost** [comment]
@javiereguiluz Yes, could tell us, how did you fix it? Thanks :)

**Comment by Muspi** [comment]
Hello @javiereguiluz , interested by solution too!

**Comment by airv-b** [comment]
Hello @javiereguiluz, how did you fix it? I interested by solution too!

**Comment by COil** [comment]
Having the deprecations too. Hi @javiereguiluz what was the @weaverryan tip? :thinking:

**Pull request closed without merging**
