### PR TITLE
CKEditorRenderer - fix contentsCss version striping

### PR DESCRIPTION
**Pull request by praznovskymartin**
Pull request for issue
CKEditorRenderer - fixConfigContentsCss strips assets version from 'contentsCss' #283

### CODE REVIEW

**Comment by egeloen** [comment]
@praznovskymartin Thanks for your PR! Can you please fix tests according to your change?

**Comment by praznovskymartin** [comment]
@egeloen Sorry about the tests, my bad... yes, I'll fix them.

The version enabling for contentsCss works fine for me. But I'm not aware of all possible use cases. 
If there should come up issues with this "fix" I suggest to make the method [fixConfigContentsCss](https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Renderer/CKEditorRenderer.php#L186) public?

**Comment by egeloen** [comment]
I'm not in favor of making this method public as it should never be used outside of the class. To summarize, there was an issue at a moment about version append to directory path (CKEditor crashes with such configurations) but according to the doc, contentsCss only accepts one or multiple files, so we can go safely with your patch as no directory path is involved here.

**Comment by egeloen** [comment]
Additionally, we should also review all usage of `fixPath` in the renderer in order to be sure we only strip versions for directories...

**Comment by egeloen** [comment]
For the record, stripping version was required by #21 but only for the `CKEDITOR_BASE_PATH` var, not sure for other paths. This would require to test manually all features which uses the `fixPath` methods...

**Comment by egeloen** [comment]
For the record, if there is no update on this PR I will finish it monday :)

**Comment by praznovskymartin** [comment]
I've fixed the tests.

**Comment by egeloen** [comment]
@praznovskymartin I just merge your work in #289. Thanks!

**Pull request closed without merging**
