### PR TITLE
Wrap widget code in $(document).ready()

### PR DESCRIPTION
**Pull request by aivus**
We got unloaded ckeditor in inline mode. It happens randomly.

/cc @whiteeagle88

### CODE REVIEW

**Comment by egeloen** [comment]
Thanks for your PR but I can't accept it. Let me explain why. Basically, the bundle has been designed to work without jQuery but then, with your code, you couple it strongly with it. What is your base issue which have motivated your PR?

**Comment by egeloen** [comment]
Sorry, I have not readed the PR's description... DO you rely on `inline: true` and `jquery: true`?

**Comment by aivus** [comment]
I use SonataAdminBundle with IvoryCKEditor.
But some fields not load ckeditor fully. Like on screenshot (bottom field).
This happens with fields, which initialized by "CKEDITOR.inline"

ckeditor-issue

**Comment by egeloen** [comment]
Okay bu tthen, do you rely on `inline: true` and `jquery: true`? I ask because you should do and then, a better fix would be to wrap the code only if the jquery option is enabled.

**Comment by egeloen** [comment]
@alvus Can you update your PR by only using `$(document).ready` if the `jquery` var is enabled? (The `jquery` var is directly accessible in the template.

**Comment by aivus** [comment]
Yes, but I can do this after weekend

С уважением, Илья Антипенко

**Comment by aivus** [comment]
PR updated.

@egeloen , what do you think about some documentation for this?
Like "If you have issues with ckeditor try to use `jquery: true`"?

**Comment by egeloen** [comment]
@aivus Yes maybe better is to recommend to use the jQuery wrapper if it relies on jQuery in their app instead of speaking about issue :) Can you add a note in the doc?

**Comment by aivus** [comment]
I'll add note asap

**Comment by aivus** [comment]
I have added note.

**Comment by egeloen** [comment]
Merged in 7ee6d1819ab5663d27e7031acf746a00ecad01a4 Thx!

**Pull request closed without merging**
