### PR TITLE
Symfony Flex compatibility (namespaced syntax)

### PR DESCRIPTION
**Pull request by pixocode**

### CODE REVIEW

**Comment by egeloen** [comment]
@pixocode Thanks! Can you take a look to the falling tests?

**Comment by pixocode** [comment]
@egeloen I forgot the test file that tested the accuracy of the parameter I changed :)

**Comment by egeloen** [comment]
Do you confirm that twig (shipped with Symfony 2.7.0) already supports namespaced templates? or do we need to bump the twig version? (The composer.json currently uses `"twig/twig": "^1.12"`)

**Comment by pixocode** [comment]
Supported on version 1 and 2
"The filesystem loader also supports namespaced templates. This allows to group your templates under different namespaces which have their own template paths."
"Namespaced templates can be accessed via the special @namespace_name/template_path notation"
https://twig.sensiolabs.org/doc/1.x/api.html
https://twig.sensiolabs.org/doc/2.x/api.html

**Comment by egeloen** [comment]
:+1 Thanks!: Can't release a new minor version right now but I will do it later this week.

**Pull request merged**
