### PR TITLE
Bring back form alias support for Symfony 2.8 which have been dropped accidentally

### PR DESCRIPTION
**Pull request by egeloen**

### CODE REVIEW

**Comment by wadjeroudi** [comment]
@egeloen Could you please make a release with this commit ?

**Comment by egeloen** [comment]
Thanks for pointing it out! I will do it tonight...

**Comment by egeloen** [comment]
@wadjeroudi Done: https://github.com/egeloen/IvoryCKEditorBundle/releases/tag/4.0.5

**Comment by wadjeroudi** [comment]
@egeloen Thanks for your reactivity.

**Pull request merged**
